name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Front & Testing
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test:prod
        continue-on-error: true
      - name: Save Code Linting Report JSON
        run: npm run lint:json -- --fix
        continue-on-error: true 
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}" 
          report-json: "./coverage/eslint-result.json"
      - name: Build Ionic project
        run: |
          ionic build --prod -- --base-href http://webapps.stoia.tech/
          cd www
          cp index.html 404.html
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/
  build-and-push-gcr-frontend:
    name: Build & Push to GCR
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_AUTH }}'
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: gcr.io
          project_id: ${{ vars.GCP_PROJECT_ID }}
          image_name: vinyl-app
          image_tag: latest, ${{ github.sha }}
          dockerfile: Dockerfile
          context: ./      
    