name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Front & Testing
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test:prod
        continue-on-error: true
      - name: Save Code Linting Report JSON
        run: npm run lint:json -- --fix
        continue-on-error: true 
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}" 
          report-json: "./coverage/eslint-result.json"
      - name: Build Ionic project
        run: |
          ionic build --prod -- --base-href http://webapps.stoia.tech/
          cd www
          cp index.html 404.html
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/
  build-and-push-gcr-frontend:
    name: Build & Push to GCR
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_AUTH }}'
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: gcr.io
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image_name: vinyl-app
          image_tag: latest, ${{ github.sha }}
          dockerfile: Dockerfile
          context: ./

  deploy-front:
    needs: [build-and-push-gcr-frontend]
    runs-on: ubuntu-latest
    name: Deploy to Server
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'un-valor-para-que-no-de-error'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
            ssh ubuntu@${{ secrets.SSH_HOST }} "if [ ! -d 'vinyl-app' ]; then \
                git clone https://github.com/razvans96/vinyl-app.git; \
              else \
                cd vinyl-app && git stash && git fetch --all && git reset --hard origin/main && git pull origin main; \
              fi"
            ssh ubuntu@${{ secrets.SSH_HOST }} "cd vinyl-app && docker-compose pull && docker-compose up -d --remove-orphans && yes | docker image prune"
        continue-on-error: true
    